[package]
authors = ["Mathieu Amiot <amiot.mathieu@gmail.com>"]
edition = "2015"
name = "moldi"
version = "0.0.2"
description = "Elegant lazy dependency injection library for Rust"
documentation = "https://docs.rs/moldi"
homepage = "https://github.com/OtaK/moldi"
include = [
    "**/*.rs",
    "Cargo.toml",
]
keywords = [
    "di",
    "container",
    "dependency",
    "injection",
    "lazy",
]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/OtaK/moldi"

[dependencies]
parking_lot = "0.12"
